"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CLIENT_PORT = exports.Diff = exports.BASE_URL = exports.PROTOCOL = exports.API_PREFIX = exports.ADDRESS = exports.PORT = exports.EVENTS = void 0;
var constants_1 = require("./src/constants");
Object.defineProperty(exports, "PORT", { enumerable: true, get: function () { return constants_1.PORT; } });
Object.defineProperty(exports, "ADDRESS", { enumerable: true, get: function () { return constants_1.ADDRESS; } });
Object.defineProperty(exports, "API_PREFIX", { enumerable: true, get: function () { return constants_1.API_PREFIX; } });
Object.defineProperty(exports, "PROTOCOL", { enumerable: true, get: function () { return constants_1.PROTOCOL; } });
Object.defineProperty(exports, "BASE_URL", { enumerable: true, get: function () { return constants_1.BASE_URL; } });
Object.defineProperty(exports, "CLIENT_PORT", { enumerable: true, get: function () { return constants_1.CLIENT_PORT; } });
var types_1 = require("./src/types");
Object.defineProperty(exports, "Diff", { enumerable: true, get: function () { return types_1.Diff; } });
var events_1 = require("./src/events");
Object.defineProperty(exports, "EVENTS", { enumerable: true, get: function () { return events_1.EVENTS; } });
